### ISSUE TITLE
function :telemetry.span/3 is undefined or private

### ISSUE THREAD

**Issue by bhritch** [bitcrowd/chromic_pdf#108]
Hi, how to solve this issue? "function :telemetry.span/3 is undefined or private" 
tried doing it in postman, tia

**Comment by andreasknoepfle** [comment]
Hello @bhritch 

Which Erlang/Elixir version are you using? 
When does the error actually happen (what functions are you calling)?
Could you maybe provide some stacktrace? 

If you can provide some answers to those questions this would help us a lot to find out what is happening.

Cheers
Andi

**Comment by bhritch** [comment]
version : 1.11.1
i tried calling it in myapp_controller.ex, tried the examples but error occur.
 (exit) an exception was raised:
    ** (UndefinedFunctionError) function :telemetry.span/3 is undefined or private
        (telemetry 0.4.0) :telemetry.span([:chromic_pdf, :print_to_pdf], %{}, #Function<8.55254136/0 in ChromicPDF.API.with_telemetry/3>)

**Comment by andreasknoepfle** [comment]
From a first look, it seems that you are using an old version of `telemetry` that does not have the `span/3` function yet. 
It was added in the `0.4.2` release of telemetry last year. Can you check what version you are currently using?
https://github.com/beam-telemetry/telemetry

**Comment by andreasknoepfle** [comment]
@maltoe probably we need to update the `deps` to account for that.

**Comment by bhritch** [comment]
Hi @andreasknoepfle it works! Thanks so much.

**Comment by andreasknoepfle** [comment]
Perfect. Updated the dependency constraint, so that from the next version no one should run into this again.
