### ISSUE TITLE
Replace `wait_for` with script evaluation

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/chromic_pdf#112]
Hi @jarimatti ,

posting this here so we can discuss it and you feel involved and not replaced (because replacing is what I intend to do 😄 ):

## on fixing the race condition in `wait_for`

I looked into the `wait_for` option a bit more and found out that in its current implementation it's definitely a bit cumbersome to use, and fixing it is unfortunately non-trivial. 

* As we discussed before, if the element already has the attribute set before we send the `querySelector` call, we won't get any `attributeModified` notification and run into a timeout. In fact, the "Example HTML" we have in the [docs](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#print_to_pdf/2) has this error if used as-is (i.e. without any `setTimeout` or JS lib doing some work in between).
* We could fix this two ways:
  - "polling": Repeatedly ask Chrome to [`DOM.getAttributes`](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getAttributes) instead of waiting for `attributeModified` -> this should work, but feels a little clunky.
  - Reading the `DOM.setChildNode` notifications we get right after `DOM.getDocument` and filter out the relevant node and its attributes. This would be my preferred approach, but turned out to be rather tricky unfortunately
    - the `DOM.setChildNode` messages come after `DOM.getDocument`, i.e. theoretically before we get the result of `DOM.querySelector` -> hence at this point in time we might not know the `nodeId` of the element in question. We could instead match the node based on the `id` attribute here.
    - `DOM.setChildNode` notifications traverse the tree, so technically we will get between one and many of them, and would need to read them all. That's another thing that the `Protocol` machine can't do right now.

In summary: Either way outlined above, in combination with some kind of `if_state` runtime conditional, is a whole lot of complexity we would introduce only to make sure the `wait_for` logic is race-free, i.e. can deal with elements which have the attribute already set. Therefore, even if I like the API interface quite a lot (as it covers a lot and doesn't need help from the client-side), **IMO** it is not worth the added complexity in the code. So, at this point I discarded the entire idea and looked for alternatives.

## Evaluating a custom script instead

Actually I had planned to support this devtools call even before you added `wait_for`, but didn't move on with it as I personally had no use for it at the time: [`Runtime.evaluate`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate). It might be a bit of a sledgehammer solution to replace `wait_for`, but of course it has potential to solve other use-cases as well. Looking into it this morning, I wanted to specifically see what it takes to mimick `wait_for` though, and here it is:

```elixir
# protocols/print_to_pdf.ex
if_option :evaluate do
  call(:evaluate, "Runtime.evaluate", [{"expression", [:evaluate, :expression]}], %{awaitPromise: true})
  await_response(:evaluated, [])
end
```

```
# client call
@wait_for_js """
async function waitForAttribute(selector, attribute) {
  while (!document.getElementById(selector).hasAttribute(attribute) {
    await new Promise(resolve => requestAnimationFrame(resolve));
  }
};

waitForAttribute('testdiv', 'ready-to-print');
"""

ChromicPDF.print_to_pdf(..., evaluate: %{expression: @wait_for_js})
```

Of course I didn't come up with this script myself: [stackoverflow link](https://stackoverflow.com/a/53269990). In my test setup, this worked for both cases; when I had the attribute already set on the element as well as with `setTimeout(... setAttribute..., 1000)`.

In my opinion, this is quite neat. What do you think? Would you be ok with replacing the `wait_for` option with this instead?One could theoretically also emulate the `wait_for` behaviour with this script underneath, i.e. put this script into ChromicPDF and make the `wait_for` option set an `evaluate` option instead. But I'm not yet convinced maintaining this in code has much added benefit over just mentioning it in the docs.

**Comment by maltoe** [comment]
@jarimatti I went ahead and added the `evaluate` option and rewrote your `wait_for` option based on a JS script. If you have time to test it out on your `wait_for` use-case, that would be super nice 🙏

**Comment by jarimatti** [comment]
This looks nice! I agree, the `wait_for` has known issues and this feels like a better and much more versatile approach. I will give this a spin.

**Comment by jarimatti** [comment]
If I'm the only one using `wait_for` (and not even that much) I'm all in for removing it completely if you think it makes sense. I can easily replace any use of it with the new approach.

**Comment by maltoe** [comment]
🤷‍♂️  idk if it has more users, @dgigafox perhaps... On the other hand the script ended up being so small that I think I'm fine with maintaining it in the code. At least this way it is tested (in contrast to when I would just use it as an example in the docs).
