### ISSUE TITLE
Fillable Forms

### ISSUE THREAD

**Issue by dabaer** [bitcrowd/chromic_pdf#115]
I've been searching around and don't really see support for fillable forms in the generated PDF, is this something that's possible to implement?

I've tried creating the forms manually but it's a huge p.i.t.b. trying to get everything aligned properly with the generated output, or even from scratch.

Would be a life-saver if we could peep form inputs and convert them to fillable fields.

**Comment by maltoe** [comment]
Hi @dabaer,

no, unfortunately this is not possible. ChromicPDF does not support it and to the best of my knowledge it is also impossible to do with Chrome / its rendering engine, for reasons I explained [here](https://elixirforum.com/t/chromicpdf/29473/16).

**Comment by dabaer** [comment]
Darn, I was hoping for something automatic since drawing pdf forms in Libreoffice is a huge pain in the hoohoo.

Thanks anyways 😭
