### ISSUE TITLE
ChromicPDF keeps crashing on Gigalixir

### ISSUE THREAD

**Issue by ppiechota** [bitcrowd/chromic_pdf#127]
Hi, could you please help me with this one. I'm trying to use your library on a free Gigalixir tier but it keeps failing on an application startup with a following error:

```
 ** (RuntimeError) Timeout in Channel.run_protocol/3!
 16:53:07.958 [error] Task #PID<0.4273.0> started from #PID<0.4239.0> terminating
 
 The underlying GenServer.call/3 exited with a timeout. This happens when the browser was
 not able to complete the current operation (= PDF print job) within the configured
 If you are printing large PDFs and expect long processing times, please consult the
 
 5000 milliseconds.
 
 documentation for the `timeout` option of the session pool.
 bug in ChromicPDF. Please open an issue on the issue tracker.
 If you are *not* printing large PDFs but your print jobs still time out, this is likely a
 
     (chromic_pdf 1.1.0) lib/chromic_pdf/pdf/browser/session_pool.ex:110: ChromicPDF.Browser.SessionPool.do_init_worker/2
     (chromic_pdf 1.1.0) lib/chromic_pdf/pdf/browser/channel.ex:24: ChromicPDF.Browser.Channel.run_protocol/3
     (elixir 1.12.1) lib/task/supervised.ex:35: Task.Supervised.reply/5
     (elixir 1.12.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
     (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
 Function: #Function<0.33738222/0 in ChromicPDF.Browser.SessionPool.init_worker/1>
     Args: []
 [0824/165309.842598:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 1731: Permission denied (13)
 16:53:13.065 [error] Task #PID<0.4275.0> started from #PID<0.4239.0> terminating 
```

I'm using mix releases deployment option to Gigalixir. Here is my config:

**env.sh.eex**
```bash
#!/bin/sh

apt-get update
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt-get -y install ./google-chrome-stable_current_amd64.deb
```

**application.ex**

```elixir
defmodule Flip.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false


  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Flip.Repo,
      # Start the Telemetry supervisor
      FlipWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Flip.PubSub},
      # Start the Endpoint (http/https)
      FlipWeb.Endpoint,
      # Start a worker by calling: Flip.Worker.start_link(arg)
      # {Flip.Worker, arg}
      {ChromicPDF, no_sandbox: true, discard_stderr: false, session_pool: [timeout: 10_000]}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Flip.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    FlipWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

So basically, I use env.sh.eex to download and install chrome and setup no_sandbox as Gigalixir uses Docker. Moreover sometimes I get no errors after deployment and everything works perfectly. But most of the times it keeps failing. I have no idea why this happens, could you have a look please?

**Comment by ppiechota** [comment]
` [0824/174800.582082:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or dir`

**Comment by maltoe** [comment]
Hi @ppiechota 

Unfortunately I have no means of debugging your issue on Gigalixir. This line seems to indicate that Chrome isn't able to adjust the OOM score of its renderer processes (it does that to give them a "priority" in which they should be killed in OOM situations):

> [0824/165309.842598:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 1731: Permission denied (13)

[This ancient chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=576409) suggests to set `CAP_DAC_OVERRIDE` to fix that, but as said, I have no clue and no way of debugging this. Also, if possible on Gigalixir, you should try to run Chrome as non-root (-> and drop the `no_sandbox: true` option). Did you try installing Chrome with a buildpack? e.g. https://github.com/hermantolim/gigalixir-buildpack-google-chrome

Sorry that I'm not of much help here.

**Comment by ppiechota** [comment]
Hi @maltoe , thanks for your answer, of course I didn't mean anybody to investigate it on the server :)  Actually, yesterday I checked  official heroku buildpack for chrome:

https://github.com/heroku/heroku-buildpack-google-chrome

and it only worked for AWS deployment, not GCP that is much closer to my place. GCP did give the same errors as above. I'll try to use the one you mentioned, thanks once again.

**Comment by maltoe** [comment]
@ppiechota 👋  did you find a solution for this?

**Comment by ppiechota** [comment]
Hi @maltoe, I stayed with AWS where chrome heroku buildpack works well. For me the issue is resolved.

**Comment by dvic** [comment]
We also encountered this, I just submitted #147 which might fix this problem by allowing you to set a higer timeout. The timeout option was being ignored before in `do_init_worker`.
