### ISSUE TITLE
Generate landscape PDF

### ISSUE THREAD

**Issue by cblavier** [bitcrowd/chromic_pdf#129]
Hi there,

I'm currently struggling at generating a PDF from an url in landscape mode.
I tried with the following options:
```
ChromicPDF.print_to_pdf(
  %{
    source: {:url, "http://acme.com/pdf"},
    opts: [
      print_to_pdf: %{landscape: true}
    ]
  }
)
```

or 

```
ChromicPDF.print_to_pdf(
  %{
    source: {:url, "http://acme.com/pdf"},
    opts: [
      print_to_pdf: %{paperWidth: 11, paperHeight: 8.5}
    ]
  }
)
```

None is working. Any idea?

**Comment by andreasknoepfle** [comment]
Which version of chromic_pdf are you using? 
In the most recent 1.1.0 there is only `print_to_pdf/2` in the docs https://hexdocs.pm/chromic_pdf/1.1.0/ChromicPDF.html#print_to_pdf/2

```
ChromicPDF.print_to_pdf(
  {:url, "http://acme.com/pdf"},
  print_to_pdf: %{landscape: true}
 )
```

**Comment by andreasknoepfle** [comment]
I just tried out your example and for me it does generate landscape layouts:

I use chrome on a mac with this version: 
```
Version 93.0.4577.82 (Official Build) (x86_64)
```

[landscape.pdf](https://github.com/bitcrowd/chromic_pdf/files/7210002/landscape.pdf)
[no-landscape.pdf](https://github.com/bitcrowd/chromic_pdf/files/7210003/no-landscape.pdf)

Could you give some more context on your environment (Chrome-Version, OS, etc ...) ?

**Comment by cblavier** [comment]
I'm using Ubuntu 20.04.3 LTS with Google Chrome 94.0.4606.54

**Comment by andreasknoepfle** [comment]
Hmm, I doubt that something is different on the chrome side. Could you build a minimal example project where landscape does not work (since I guess you have probably some more code around it), so we can reproduce this and help? 

I just tried as well with Chrome on a mac  version `94.0.4606.54 (Official Build) (x86_64)` and still can produce landscape pdfs 🤷  so it is a bit hard to reproduce your problem.

**Comment by cblavier** [comment]
Thanks for your help, the landscape option was correctly set and propagated.
The issue was a CSS issue

**Comment by maltoe** [comment]
Glad you could figure it out!

> The issue was a CSS issue

Anything we should put into the documentation?

**Comment by cblavier** [comment]
Not really, we just had to cleanup our mess 😉
