### ISSUE TITLE
Support Stream

### ISSUE THREAD

**Issue by danferreira** [bitcrowd/chromic_pdf#136]
Thanks for the awesome job
Really useful lib

I'm bringing here what we discussed on the forum:

Sometimes I need to print very large pdf files and the memory consumption jumps too high

It would be nice if we could support [transferMode as ReturnAsStream](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF)

(I've tried to look at the code but, because of my lack of experience in elixir, I could not find an easy way to implement IO.read/IO.close in the current macro schema)

**Comment by maltoe** [comment]
hey @danferreira 

Completed the first steps towards this. Extending the "protocol" interpreter thing with a loop for the `IO.read` calls was quite straightforward, I'm only struggling a bit now with how to integrate this into the API.

Could you elaborate a bit more on your use-case? I'd be particularly interested in how you currently handle the data (i.e. which `output` option you use, where the data goes afterwards, etc.). My current idea would be to make the `output` option also take a `pid` and send the chunks there, but there are also different paths we could take.

**Comment by danferreira** [comment]
Im migrating this particular application from nodejs/puppeteer to elixir/chromic_pdf.
I was looking for a way to mimic this new [behaviour](https://pptr.dev/#?product=Puppeteer&version=v11.0.0&show=api-pagecreatepdfstreamoptions) from puppeteer

Nowadays we do something like this:

```elixir
with {:ok, data} <- ChromicPDF.print_to_pdf({:html, content}, print_to_pdf: pdf_opts},  telemetry_metadata: %{template: template_name}),
{:ok, binary} <- Base.decode64(data) do
 conn
      |> put_resp_content_type("application/pdf")
      |> put_resp_header(
        "content-disposition",
        "attachment; filename=\"report.pdf\";"
      )
      |> send_resp(200, binary)

```
I wish I could stream the chunks to the user, stream to a s3 bucket (using [ExAws.S3#upload/4](https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#upload/4)) or stream to a file.

**Comment by maltoe** [comment]
@danferreira  Could you give #139 a try? `print_to_pdf_as_stream` takes a function that gets a `Stream` that can be sent to the conn. Please also see if the example works, I didn't test it. I have doubts though that this is going to improve your memory situation, as it seems Chrome is generating the entire file first (long delay when you fetch the first stream element, subsequent elements go fast)..

API isn't polished yet, I'd like to see if it improves your memory usage first.

**Comment by danferreira** [comment]
>  I have doubts though that this is going to improve your memory situation, as it seems Chrome is generating the entire file first (long delay when you fetch the first stream element, subsequent elements go fast)..
 
Yep, you are right. After my last comment I tested with puppeteer and got the same behavior
I thought for a moment, that chrome would deliver the chunks during the print process but, apparently, it needs to print the whole file first.

I think the real gain in memory here would be in streaming directly from Chrome to destiny instead of duplicate the whole binary in elixir/beam side.
Maybe with 2-5 reports/sec this could be a worthwhile memory improvement.
(but consumption in Chrome side would remain the same)

I will take a look at this branch

**Comment by maltoe** [comment]
> I think the real gain in memory here would be in streaming directly from Chrome to destiny instead of duplicate the whole binary in elixir/beam side.

🤔  To me it appears as if the PDF renderer in Chrome is simply not capable of streaming, TBH. So yes, while this would technically reduce the memory footprint even further, although not much. With this branch you should be able to reduce Elixir memory usage to a mininum.

By the way, in my experiments it also seems that Chrome chooses to send the entire blob as one packet (see https://chromedevtools.github.io/devtools-protocol/tot/IO/#method-read where it says "[size] left upon the agent discretion") -> so be sure to set the the size

```
config :chromic_pdf, stream_read_size: 50000
```

**Comment by maltoe** [comment]
@danferreira any news?

**Comment by maltoe** [comment]
@danferreira I'm going to close my PR, I think. Don't really see the benefit of it. Feel free to re-open this issue if you have any news.
