### ISSUE TITLE
Add more absolute paths to Chrome

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/chromic_pdf#151]
https://community.fly.io/t/cant-install-chrome-chromium-via-dockerfile-or-ssh/5303/5

Not sure how this happened ^^, theoretically [`System.find_executable/1`](https://hexdocs.pm/elixir/1.13/System.html#find_executable/1) should be able to pick up the `/usr/bin/google-chrome` path from `$PATH` :shrug:

**Comment by andreasknoepfle** [comment]
Nice find 👍
