### ISSUE TITLE
Rendering a combined PDF of multiple "files"

### ISSUE THREAD

**Issue by markquezada** [bitcrowd/chromic_pdf#177]
This is more of a question I suppose. I currently generate a PDF for a specific user based on their account information. 

I have the need to generate a single PDF of a group of these individual PDFs for archival purposes. Currently I'm rendering them individually to disk and then concatenating them via a `System.cmd` call to `qpdf`.

I thought about rendering one long PDF but I'm currently using both the header (for user profile info) and footer (for page numbers) to generate the pdf so I don't believe that'll work since headers and footers span the entire document.

Is there any way for me to leverage chromicPDF to generate this combined file directly?

**Comment by maltoe** [comment]
Hi @markquezada 

No, Chrome won't be of any help. I suppose you can join PDFs with Ghostscript (which you may have installed?), but TBH it's probably easier to use `qpdf` or `pdfjoin` and do it in a postprocessing step as you do. Sorry.

Best,
malte

**Comment by markquezada** [comment]
Figured, thanks!

**Comment by maltoe** [comment]
@markquezada FYI #194
