### ISSUE TITLE
Support dynamic names

### ISSUE THREAD

**Issue by dvic** [bitcrowd/chromic_pdf#227]
I have the usecase that I need to start ChromicPDF under a supervision tree that is started multiple times (at runtime) under different names.

If I'm not mistaken, currently it's not possible to start ChromicPDF multiple times using a different name.

Are there plans to support this? (I could work on this) To keep things simple for the users, we could adopt the same approach as Ecto (with put_dynamic_repo/1).

**Comment by maltoe** [comment]
Hi @dvic 

> started multiple times (at runtime) under different names

I'm guessing _dynamic_ names, yes? If static, you could just use the existing functionality of [`ChromicPDF.Supervisor`](https://hexdocs.pm/chromic_pdf/ChromicPDF.Supervisor.html)

> Are there plans to support this? (I could work on this) To keep things simple for the users, we could adopt the same approach as Ecto (with put_dynamic_repo/1).

Sure, why not, and yes feel free to submit a PR. Should be relatively straightforward to do with what is already there (e.g. [here](https://github.com/bitcrowd/chromic_pdf/blob/main/lib/chromic_pdf/supervisor.ex#L108)). Except maybe for the `on_demand` stuff, but I'm sure you can work around this somehow.

**Comment by dvic** [comment]
> I'm guessing _dynamic_ names, yes? If static, you could just use the existing functionality of [`ChromicPDF.Supervisor`](https://hexdocs.pm/chromic_pdf/ChromicPDF.Supervisor.html)

Correct

> Sure, why not, and yes, feel free to submit a PR. Should be relatively straightforward to do with what is already there (e.g. [here](https://github.com/bitcrowd/chromic_pdf/blob/main/lib/chromic_pdf/supervisor.ex#L108)). Except maybe for the `on_demand` stuff, but I'm sure you can work around this somehow.

👍
