### ISSUE TITLE
Timeouts on prod

### ISSUE THREAD

**Issue by silverdr** [bitcrowd/chromic_pdf#237]
Out of a sudden (cannot really be sure when it started) I began receiving timeouts on production like the one below. Things that _might_ have changed are

- phoenix version 1.6.x => 1.7.2
- sentry installed according to https://docs.sentry.io/platforms/elixir/
- maybe chromium version

but I tried rolling back all the above changes, removing all Sentry related lines, downgreading chromium, downgrading Phoenix, downgrading ChromicPDF, extending timeout, ...

Also the setup with 1.7.2 and latest chromium works on dev environment. Does anything from the log below ring any bells what might be causing the timeouts? Any clues what else to try?

```
Mar 23 22:43:10 cld bash[12537]: ** (exit) an exception was raised:
Mar 23 22:43:10 cld bash[12537]:     ** (ChromicPDF.Browser.ExecutionError) Timeout in Channel.run_protocol/3!
Mar 23 22:43:10 cld bash[12537]: The underlying GenServer.call/3 exited with a timeout. This happens when the browser was
Mar 23 22:43:10 cld bash[12537]: not able to complete the current operation (= PDF print job) within the configured
Mar 23 22:43:10 cld bash[12537]: 30000 milliseconds.
Mar 23 22:43:10 cld bash[12537]: If you are printing large PDFs and expect long processing times, please consult the
Mar 23 22:43:10 cld bash[12537]: documentation for the `timeout` option of the session pool.
Mar 23 22:43:10 cld bash[12537]: If you are *not* printing large PDFs but your print jobs still time out, this is likely a
Mar 23 22:43:10 cld bash[12537]: bug in ChromicPDF. Please open an issue on the issue tracker.
Mar 23 22:43:10 cld bash[12537]: ---
Mar 23 22:43:10 cld bash[12537]: Current protocol:
Mar 23 22:43:10 cld bash[12537]: %ChromicPDF.Protocol{
Mar 23 22:43:10 cld bash[12537]:   steps: [
Mar 23 22:43:10 cld bash[12537]:     await: &ChromicPDF.Navigate.page_load_event/2,
Mar 23 22:43:10 cld bash[12537]:     call: &ChromicPDF.PrintToPDF.print_to_pdf/2,
Mar 23 22:43:10 cld bash[12537]:     await: &ChromicPDF.PrintToPDF.printed/2,
Mar 23 22:43:10 cld bash[12537]:     call: &ChromicPDF.ResetTarget.reset_history/2,
Mar 23 22:43:10 cld bash[12537]:     await: &ChromicPDF.ResetTarget.history_reset/2,
Mar 23 22:43:10 cld bash[12537]:     call: &ChromicPDF.ResetTarget.blank/2,
Mar 23 22:43:10 cld bash[12537]:     await: &ChromicPDF.ResetTarget.blanked/2,
Mar 23 22:43:10 cld bash[12537]:     await: &ChromicPDF.ResetTarget.fsl_after_blank/2,
Mar 23 22:43:10 cld bash[12537]:     output: &ChromicPDF.PrintToPDF.output/1
Mar 23 22:43:10 cld bash[12537]:   ],
Mar 23 22:43:10 cld bash[12537]:   state: %{
Mar 23 22:43:10 cld bash[12537]:     :__protocol__ => ChromicPDF.PrintToPDF,
Mar 23 22:43:10 cld bash[12537]:     :capture_screenshot => %{},
Mar 23 22:43:10 cld bash[12537]:     :html => "[FILTERED]",
Mar 23 22:43:10 cld bash[12537]:     :info => "[FILTERED]",
Mar 23 22:43:10 cld bash[12537]:     :last_call_id => 12,
Mar 23 22:43:10 cld bash[12537]:     :output => "[FILTERED]",
Mar 23 22:43:10 cld bash[12537]:     :print_to_pdf => %{
Mar 23 22:43:10 cld bash[12537]:       "displayHeaderFooter" => true,
Mar 23 22:43:10 cld bash[12537]:       "footerTemplate" => "[FILTERED]",
Mar 23 22:43:10 cld bash[12537]:       "headerTemplate" => "[FILTERED]",
Mar 23 22:43:10 cld bash[12537]:       "paperHeight" => 11.6945,
Mar 23 22:43:10 cld bash[12537]:       "paperWidth" => 8.2768,
Mar 23 22:43:10 cld bash[12537]:       "printBackground" => true
Mar 23 22:43:10 cld bash[12537]:     },
Mar 23 22:43:10 cld bash[12537]:     :source_type => :html,
Mar 23 22:43:10 cld bash[12537]:     "frameId" => "F4AEF7C474AE93E6C26461F6D2652E61",
Mar 23 22:43:10 cld bash[12537]:     "sessionId" => "750284A85578A6837D388A114CA09E07"
Mar 23 22:43:10 cld bash[12537]:   }
Mar 23 22:43:10 cld bash[12537]: }
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/pdf/browser/channel.ex:23: ChromicPDF.Browser.Channel.run_protocol/3
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/pdf/browser/session_pool.ex:63: anonymous fn/4 in ChromicPDF.Browser.SessionPool.run_protocol/3
Mar 23 22:43:10 cld bash[12537]:         (nimble_pool 0.2.6) lib/nimble_pool.ex:349: NimblePool.checkout!/4
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/pdf/browser/session_pool.ex:58: ChromicPDF.Browser.SessionPool.run_protocol/3
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/api.ex:67: anonymous fn/3 in ChromicPDF.API.chrome_export/4
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/api/telemetry.ex:10: anonymous fn/2 in ChromicPDF.Telemetry.with_telemetry/3
Mar 23 22:43:10 cld bash[12537]:         (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
Mar 23 22:43:10 cld bash[12537]:         (chromic_pdf 1.7.0) lib/chromic_pdf/api.ex:93: anonymous fn/4 in ChromicPDF.API.print_to_pdfa/3
```

**Comment by maltoe** [comment]
Hi @silverdr,

unfortunately we also see (apparently random) timeouts in our own apps, which are extremely difficult to diagnose and fix. Some people in the past had issues with timeouts in CI in particular, and often only on the first PDF job (see for instance #160 ), but at times Chrome still seems to inexplicable hang and not send us the messages we're waiting for.

A few things

* The protocol in your log is waiting for the `Page.loadEventFired` notification which indicates the page has in fact not fully loaded (or we somehow didn't get the notification) - but 30s timeout seems long enough and I'm assuming you don't try to print 200 pages or so.
* A good thing to have (for you and us) would be metrics about to how often this happens, to evaluate the severity of the problem.
* In our case, these timeouts are *extremely* rare, and we often believe they happen around deployments (though we're not sure about that), which makes them less of a problem for us. Also, we generally put ChromicPDF behind a job queue with retries.

I wish I could say I truly had an idea what causes these timeouts, or how to fix them. But unfortunately no :/

hope this helps a bit,
malte

**Comment by silverdr** [comment]
> I'm assuming you don't try to print 200 pages or so

Definitely no. Those are the same types of documents, which I was happy to normally get under one second. I only now increased the timeout to 30s from the default five "just in case" but to no change
> A good thing to have (for you and us) would be metrics about to how often this happens, to evaluate the severity of the problem

At this very moment this is 100% on prod - no single document gets out. The browser is:
```
root@954d2755e171:/app# chromium --version
find: ‘/root/.config/chromium/Crash Reports/pending/’: No such file or directory
Chromium 111.0.5563.110 built on Debian 11.6, running on Debian 11.6
```
yet I tried downgrading to `108.0.5359.124-1` - no change. I wish I could pinpoint the exact moment the problem started but I can't :-(

FWIW - I get this upon starting the  browser:
```
[0323/225510.025994:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
a few times but I believe they were there before too. Pardon a potentially lame question - you don't use dbus to talk to chrome, do you?

**Comment by andreasknoepfle** [comment]
We are using the chrome devtools protocol https://chromedevtools.github.io/devtools-protocol/ to talk to chrome through a remote debugging pipeline similar to how it is described here https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

Not sure if internally chrome uses `dbus` to support that, but that maybe a good first thing to try.

**Comment by maltoe** [comment]
> Not sure if internally chrome uses dbus to support that

We don't have dbus running in any of our containers, and get the same errors from chromium. Our images are alpine-based, though.

**Comment by maltoe** [comment]
@silverdr Can you try printing a really simple document, just to rule out that it is somehow caused by your template?

```
ChromicPDF.print_to_pdf({:html, "hello"})
```

**Comment by silverdr** [comment]
```
Interactive Elixir (1.14.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(phxapp@954d2755e171)1> ChromicPDF.print_to_pdf({:html, "hello"})
{:ok,
 "JVBERi0xLjQKJdPr6eE[…]aLEiu3xvrYWn9IhGOYR1nNZmpOa8YwjgK6QDm98FKJ6JkPz+7duZT6tMf30VRrud6rud6rud6rv8f99WSLEPSwUgoahj4nC/e3yEd" <> ...}
iex(phxapp@954d2755e171)2>
```
I guess this says - "OK"

**Comment by maltoe** [comment]
> I guess this says - "OK"

It does. Any noteworthy changes to your template recently? Especially JavaScript stuff?

**Comment by silverdr** [comment]
Wondering if that could be somehow caused by the template (which seem to all work fine on dev env) what could this be. There were no changes to the template. The only template-about changes were related to static assets when migrating to PHX1.7 but I think the first container which exhibited the issue had still 1.6.

**Comment by silverdr** [comment]
Is there a way to somehow get the browser's console output, maybe?

**Comment by silverdr** [comment]
FYI - as a matter of fact it must have gotten broken with migration to 1.7 but wasn't noticed immediately as everything works on dev env all the time and errors started flowing once somebody actually needed to generate PDF on prod. Must have something to do with the changes in static assets handling and chrome apparently waited for the css, which was not served anymore. Works now. Thank you for your support and hind with `ChromicPDF.print_to_pdf({:html, "hello"})` 🙇

**Comment by maltoe** [comment]
Glad you could resolve your issue. :+1:

**Comment by maltoe** [comment]
@silverdr matter of fact, maybe could you elaborate a bit more into what happen with the static asset request? Maybe we can improve that timeout error message a bit, mentioning this scenario as a possible cause.

> the changes in static assets handling and chrome apparently waited for the css

Did the request hang indefinitely?
