### ISSUE TITLE
Chromium on a different machine in the network

### ISSUE THREAD

**Issue by gmile** [bitcrowd/chromic_pdf#249]
First of all - amazing work!

It never occurred to me that using Chromium without firing up Puppeteer to render PDFs was possible. Knew about DevTools Protocol, but never connected the dots that one can actually implement that protocol to talk Chromium directly. Makes perfect sense in hindsight!

A question: would it be possible, if not currently then in principle, to talk to a Chromium that resides on an another computer on the network? E.g. a setup where Chromium would essentially represent a microservice? Or is talking via JsonRPC limited & can be done only to a local instance of Chromium?

**Comment by MaeIsBad** [comment]
It is possible to have chrome run on a separate machine on the network in principle, but it's not implemented currently.

The chrome devtools protocol can run over the network instead of using a pipe if you set the `--remote-debugging-port=9222` and `--remote-debugging-address` options, but currently chromic_pdf only supports the pipe method

**Comment by maltoe** [comment]
Exactly ^^ AFAIK historically Chrome did not even support true remote debugging (i.e. 9222 was bound to 127.0.0.1, likely for security reasons), `--remote-debugging-address` was introduced later. Adding support to chromic_pdf would be feasible in theory, though I personally think building a small Elixir service yourself to encapsulate it is much preferable. What makes you think about this solution @gmile ?

**Comment by gmile** [comment]
> What makes you think about this option, if I may ask?

With `chromium`-as-a-service available on the network, we'd essentially be trading performance of having `chromium` available as a sibling process in the same OS for:

* having a smaller, simpler Docker image,

* ability to scale `chromium` service independently of the our main app (it so happens that scaling our main app is not easy due to some architecture decisions).

Another advantage of this is, because there are examples of dockerising `chromium` (for instance, [this](https://hub.docker.com/r/linuxserver/chromium)), it should be relatively straightforward to deploy it with a debugger port exposed, without the need of having a think HTTP wrapper around it.

**Comment by maltoe** [comment]
[This one](https://hub.docker.com/r/nextools/chromium) looks more targeted at your use-case.

Not sure if I'm going to find the time to work on this, but FWIW I tried scaffolding a `gen_tcp` based implementation of `ChromeRunner` in https://github.com/bitcrowd/chromic_pdf/commit/59803d6f1a56b0aab435636166bd6321b7660fd0 . Luckily there's a undocumented DI mechanism in place, so you can just do

```
ChromicPDF.start_link(chrome_runner: ChromicPDF.ChromeTCP)
```

to try it out. Could not get it to work unfortunately, `tcp_closed`.

**Comment by maltoe** [comment]
Nevermind ^^ `:9222` wants a websocket client

**Comment by gmile** [comment]
@maltoe thanks for looking into this! I will definitely try find the time this week to check out the `nextools/chromium` branch :+1:

> But this will be more work than expected, also requires quite a bit of refactoring in Connection to make it pretty.

My knowledge about `chromic_pdf` architecture is quite limited rn, could you elaborate what do you in mind for refactoring the Connection to make it pretty? Do you mean like refactoring it in a way that separates handling of messages coming from WS and from port?

**Comment by maltoe** [comment]
@gmile Branch is called [`249-chromium-on-a-different-machine-in-the-network`](https://github.com/bitcrowd/chromic_pdf/compare/feature/249-chromium-on-a-different-machine-in-the-network), [`nextools/chromium`](https://hub.docker.com/r/nextools/chromium) is the docker image I've used.

Refactoring: `ChromeRunner` should encapsulate the local chrome/chromium process spawned via a `Port`, but some parts of it have leaked into `Connection`. E.g., the entire port message handling is located there as well as the message "tokenization" (which isn't needed at all for ws connections as messages will arrives in frames). At first glance I'd say that `ChromeRunner` should be the active process, take care of tokenization and port event handling; and `Connection` instead be passive and only take care of JsonRPC transcoding and delegating to its connection "strategy" (-> probably rename `ChromeRunner` behaviour nested in `Connection`).

**Comment by maltoe** [comment]
@gmile any updates on this?

**Comment by maltoe** [comment]
This working for us in one of our projects.
