### ISSUE TITLE
Ability to pass URL as the template source?

### ISSUE THREAD

**Issue by osbre** [bitcrowd/chromic_pdf#260]
Hi, is it possible to pass an URL as the template source? The reason for doing that, is it has a very nice customization options.

**Comment by maltoe** [comment]
Hi @osbre ,

no, I'm afraid not. Also not sure how that would work, i.e. how `ChromicPDF.Template` would inject its CSS into the markup behind your URL.
 
But it's not doing much anyway. I'd suggest you use it to help derive a set of options and insert the CSS into your markup manually.
