### ISSUE TITLE
Ability to call `Emulation.setScriptExecutionDisabled` on a per-page basis?

### ISSUE THREAD

**Issue by osbre** [bitcrowd/chromic_pdf#267]
Hello. I'm wondering whether it's possible to set `:disable_scripts` not globally for all pages, but only on specific pages.

I'm guessing it would've been possible by calling `Emulation.setScriptExecutionDisabled` when needed?	
(make it a parameter for `print_to_pdf`)

I've tried to attempt on contributing this feature in `ChromicPDF.Navigate`, however, failed to do so due to a limited experience with Elixir. (some things are beyond my understanding - it looks like there is a restriction on what can be called inside the `Navigate` module, and this list is in the `@type navigate_option` from `Supervisor`?)

As a side note, looks like there are more methods that can be called this way, I've noticed in this script:
https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/EmulationManager.ts#L208
<img width="289" alt="list of methods in EmulationManager.ts" src="https://github.com/bitcrowd/chromic_pdf/assets/23292709/2ec1b316-7551-44fb-9df5-de485dabf012">

**Comment by MaeIsBad** [comment]
This was how I implemented this feature in the original PR, so I think this could be implemented by reverting
https://github.com/bitcrowd/chromic_pdf/pull/168

**Comment by osbre** [comment]
Thank you @MaeIsBad, sent a PR: https://github.com/bitcrowd/chromic_pdf/pull/268

**Comment by maltoe** [comment]
See discussion in PR, this can now be done by using multiple session pools.
