### ISSUE TITLE
Inspector.targetCrashed received when `no_sandbox: true` on Chromium 115 on Linux

### ISSUE THREAD

**Issue by aptinio** [bitcrowd/chromic_pdf#270]
I'm getting `[error] ChromicPDF received an 'Inspector.targetCrashed' message.` when I start my Phoenix app. If I downgrade Chromium to 114, or replace `no_sandbox: true` with `chrome_args: "--no-sandbox"`, the error is gone. If I add `"--no-zygote"` to `chrome_args`, the error is back.

I don't really know what to make of all this, but I hope it helps.

**Comment by maltoe** [comment]
Hey @aptinio,

can you share some details on your setup? Chromium version that has the error, but also host OS, environment, Elixir version, etc.. So we can try to reproduce this error.

**Comment by aptinio** [comment]
This happens on my dev environment:
- Arch Linux
- asdf-managed Elixir and Erlang/OTP versions:
  - 1.15.4-otp-25 and 25.3.2.5
  - 1.15.4-otp-26 and 26.0.2
- Chromium 115.0.5790.170

and on prod too:
- Docker image hexpm/elixir:1.15.4-erlang-26.0.2-debian-bookworm-20230612-slim
- same Chromium version 115.0.5790.170

My `chromic_pdf_options`:

```elixir
defp chromic_pdf_options do
  [
    disable_scripts: true,
    no_sandbox: true,
    offline: true
  ]
end
```

Thanks @maltoe!

**Comment by aptinio** [comment]
For now, I did this:

```diff
   defp chromic_pdf_options do
     [
       disable_scripts: true,
-      no_sandbox: true,
+      chrome_args: "--no-sandbox",
       offline: true
     ]
   end
```

**Comment by maltoe** [comment]
@aptinio Thanks for the report. I've been able to reproduce this bug on Debian Bookworm. I have not attempted to find the bug / changed behaviour within chrome or the more recent environment, and also have not found any matching issue in their trackers.

At the same time, I can't recall why the `--no-zygote` flag is present there at all. Puppeteer doesn't seem to have equivalent code, and the docs I could find just say that when you use `--no-zygote`, you must use `--no-sandbox` as well (but not vice versa). So, I think `--no-zygote` is a mistake here and am tempted to simple go for #272, though breaking existing setups is a concern of cause. I did check on Alpine 3.16 and Debian Buster that `--no-zygote` isn't needed to run an unsandboxed root chrome, so it may be fine.

@andreasknoepfle wdyt? Remove the flag and risk breaking people's setups (certainly _change_ people's setup though, as removing `--no-zygote` will add the zygote process) or play it safe?

**Comment by maltoe** [comment]
"Playing it safe" could be: Deprecate `--no-sandbox` with a warning and change the docs to just tell people to use `chrome_args` as in @aptinio 's snippet.

**Comment by maltoe** [comment]
Decided to YOLO it this time as tests in our CI environments suggest that `--no-zygote` was never needed and hence it seems unlikely that anyone will notice it.

**Comment by aptinio** [comment]
It does. Thanks @maltoe! :relaxed:
