### ISSUE TITLE
Troublesome PNG images?

### ISSUE THREAD

**Issue by toranb** [bitcrowd/chromic_pdf#293]
First up, huge thanks for all the maintainers of this awesome library. I don't maintain anything in the Elixir ecosystem and even back when I did more OSS I never had such a huge project on my plate so thank you, thank you, thank you :) for all that you do here.

I spent the last few days debugging what I now think is a PNG that won't render in chrome for whatever reason. It started with a ChromicPDF timeout, but later became a `Printing failed (Code -32000)` error and I tried a handful of issues without fully diving deeper into the PNG itself. *edit* And to make it all the more fun it only hung in production.

I quickly found this sanity test (using any png, jpg or gif from a public website) proved chrome was able to print the PDF fine

```
ChromicPDF.print_to_pdf({:html, "<div><img src=\"https://ir.ebaystatic.com/rs/v/fxxj3ttftm5ltcqnto1o4baovyl.png\" /></div>"})
```

I'm writing today to see how people diagnose images that don't render in chrome to better prevent timeouts, etc. I'm also curious if others have run into this so I can know what exactly is broken with the PNG I'm trying to render. 

Huge thanks for any feedback, apologies if this is the wrong place to post a question like this.

**Comment by maltoe** [comment]
Hi @toranb ,

thank you for your kind words :purple_heart: 

With regards to your issue, so far, we never had any issues with PNGs in our apps. It does sound like you're facing an issue with Chromium itself though, not with ChromicPDF. To further diagnose it, I'd follow the usual "procedure":

1. Find a way to reproduce it locally, not just on prod.
2. Eliminate variables from the equation, one by one, until  you've found the culprit.  I'd start by trying to reproduce the issue by only printing the offending PNG (without surrounding markup) just like you did with the public images.
3. Eventually, also removing ChromicPDF from the equation may help you find a larger audience where you can raise the issue - e.g. if you can reproduce it with puppeteer, you could ask for help over there and your issue would get way more exposure than here.

Hope this helps.

**Comment by toranb** [comment]
great call out to grow the scope of community with this PNG issue! thanks again for the quick reply!
