### ISSUE TITLE
Remote Chrome print_to_pdf fails when using Templete

### ISSUE THREAD

**Issue by wwaldner-amtelco** [bitcrowd/chromic_pdf#318]
When using the remote Chrome setup, there seems to be an issue when using templates....

**This works OK**
`ChromicPDF.print_to_pdf({:html, "<h1>hello</h1>"})  `                                                        
 {:ok,
 "JVBERi0xLjQKJdPr6eEKMSAwIG9....}

**Not working**, I don't understand error. I tried setting the chrome_version of the remote instance, but that did not work.
`[content: "<h1>hello</h1>"] |> ChromicPDF.Template.source_and_options() |> ChromicPDF.print_to_pdf()`
** (RuntimeError) Failed to determine Chrome version.

If you're using a remote chrome instance, please configure ChromicPDF manually:

    config :chromic_pdf, chrome_version: "Google Chrome 120.0.6099.71"

Afterwards, force a recompilation with:

    mix deps.compile --force chromic_pdf

--- original exception --

** (RuntimeError) could not find executable from ["chromium-browser", "chromium", "chrome.exe", "google-chrome", "/usr/bin/chromium-browser", "/usr/bin/chromium", "/usr/bin/google-chrome", "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "/Applications/Chromium.app/Contents/MacOS/Chromium"]
    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/chrome_runner.ex:84: ChromicPDF.ChromeRunner.executable/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/chrome_runner.ex:35: ChromicPDF.ChromeRunner.do_version/0
    (chromic_pdf 1.15.2) lib/chromic_pdf/utils.ex:127: ChromicPDF.Utils.with_app_config_cache/2
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:368: ChromicPDF.Template.default_zoom/0
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:360: ChromicPDF.Template.assigns_for_styles/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:321: ChromicPDF.Template.page_styles/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:171: ChromicPDF.Template.source_and_options/1
    (elixir 1.14.2) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1

    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/chrome_runner.ex:84: ChromicPDF.ChromeRunner.executable/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/pdf/chrome_runner.ex:35: ChromicPDF.ChromeRunner.do_version/0
    (chromic_pdf 1.15.2) lib/chromic_pdf/utils.ex:127: ChromicPDF.Utils.with_app_config_cache/2
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:368: ChromicPDF.Template.default_zoom/0
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:360: ChromicPDF.Template.assigns_for_styles/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:321: ChromicPDF.Template.page_styles/1
    (chromic_pdf 1.15.2) lib/chromic_pdf/template.ex:171: ChromicPDF.Template.source_and_options/1

**Comment by maltoe** [comment]
:thinking: it seems as if it would still try to read `:chrome_version` from chrome itself (by spawning a local instance, which doesn't work). Are you sure you have forced recompilation? If in doubt, just clean the dependency itself, `mix deps.clean chromic_pdf`.

**Comment by wwaldner-amtelco** [comment]
I was recompiling, but did not have the config set in the application's config.ex file. So now that I hard-coded the version in the config, 

```
config :chromic_pdf,
  chrome_address: {"localhost", "9222"},
  chrome_version: "Chromium 119.0.6045.159 Alpine Linux"
```


I get this error
```
iex(prod@ip-10-10-2-118)2> [content: "<h1>hello</h1>"] |> ChromicPDF.Template.source_and_options() |> ```
ChromicPDF.print_to_pdf()
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("Chromium 119")
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (chromic_pdf 1.16.1) lib/chromic_pdf/utils.ex:141: ChromicPDF.Utils.semver_compare/2
    (chromic_pdf 1.16.1) lib/chromic_pdf/template.ex:368: ChromicPDF.Template.default_zoom/0
    (chromic_pdf 1.16.1) lib/chromic_pdf/template.ex:360: ChromicPDF.Template.assigns_for_styles/1
    (chromic_pdf 1.16.1) lib/chromic_pdf/template.ex:321: ChromicPDF.Template.page_styles/1
    (chromic_pdf 1.16.1) lib/chromic_pdf/template.ex:171: ChromicPDF.Template.source_and_options/1
    iex:2: (file)
```

**Comment by wwaldner-amtelco** [comment]
OK, after specifying the version without "Chromium" prefix, it is working
chrome_version: "119.0.6045.159"
