### ISSUE TITLE
Converting to PDF/A without ligatures

### ISSUE THREAD

**Issue by silverdr** [bitcrowd/chromic_pdf#329]
Using `print_to_pdfa` successfully but with a caveat, which is a true PITA - the output files are using ligatures. This ruins parsing of those files or even the simplest copy-paste of text later on as there are apparently missing "to unicode" mappings – this is what I read in various sources might be the reason for such symptoms.

Is there any way to make the conversion to preserve correct mappings there?

It seems that pre-conversion (as output from `print_to_pdf`) the PDF still has all the information intact. The problem happens when converted to PDF/A, which (I guess) - optimises the embedded font(s) and strips whatever it doesn't see as necessary? As a workaround I disabled all ligatures in CSS and the text remains processable but the rendering is no longer as pretty as originally.

**Comment by maltoe** [comment]
Hi @silverdr,

sorry, this is beyond my (ghostscript and PDF) knowledge. To the best of my knowledge, we also never had any issues with ligatures or non-copyable text in PDF/As. This is likely all dependent on the font you're using, right?

If you play with ghostscript command line args and discover anything that chromic_pdf should have proper support for, please let me know.

**Comment by silverdr** [comment]
FYI - it's not that the text is non-copyable. It's that wherever there is a ligature, the original letters, for which the ligature was substituted are gone/garbled. They are missing on pasting copied text, on parsing / extracting the text from the PDF, etc. This may or may not happen, depending on the actual, original text and whether it contains words "ligatrurisable" pairs "ff", "ft", "fi", etc. It might also depend on the font as you mentioned. If the font does not define ligatures, they obviously cannot be used so this can obscure the problem too. But fonts with well defined ligatures allow rendering better looking documents so they are understandably preferred.

Anyway – Roger – I understand. I'll let you know if I find in Ghostscript something that could make it work correctly. Regards.
