### ISSUE TITLE
Trigger Pdf Generation and Download the Pdf File on Browser via Button

### ISSUE THREAD

**Issue by alvnrapada** [bitcrowd/chromic_pdf#52]
This is probably a dumb question but i'll ask anyway. 

My goal: 
My users have multiple records, and each records on display has a download button. when user clicks the button it will generate the pdf containing specific record inside and triggers download on the browser. 

Is there a way to do that using this. when trying to pipe this on my controller it only saves a file on the project folder. Thank you so much!!

**UPDATE:** 

I was able to trigger browser upload by passing the base64 encoded pdf to an a tag:

```
/template.html.eex
   <% html = (render Web.SharedView, "_pdf_template.html",  assigns) %>
   <a href="data:application/pdf;base64,<%= render_pdf(html) %>" download>DOWNLOAD</a>


/render_view.ex
  def render_pdf(html) do
    ChromicPDF.print_to_pdf({:html, html})
    |> elem(1)
  end
```

**PROBLEM:**
Images inside the pdf file are all corrupted.

**Comment by maltoe** [comment]
@alvnrapada 🤔  I'm not entirely sure I understand what you're trying to achieve, but maybe I can give you some hints at least

First, the way to download the PDF: You probably shouldn't render the PDF before the user has clicked the "DOWNLOAD" link, but when they click it. Also I wouldn't render it in the template, for sure, but rather in a controller. How about something like this

```elixir
# template.html.eex
<%= link "Download", Routes.user_download_record_path(@conn, @user) %>

# router.ex
get "/users/:id/download_record", UsersController, :download_record

# users_controller.ex
def download_record(conn, _params) do
  # ... however you built your assigns before
  assigns = %{foo: :bar}

  html = Web.SharedView.render("_pdf_template.html", assigns)

  ChromicPDF.print_to_pdf({:html, html}, output: fn tmpfile ->
    conn
    |> put_resp_content_type("application/pdf")
    |> send_file(200, tmpfile)
  end)
end
```

With regards to the images being corrupted: I did not experience any issues with Chrome not being able to store images in the PDF. Hence I would think that your rendered HTML does not contain the images / any valid URL to them. Keep in mind, when you use the `{:html, html}` syntax, it replace the HTML content in the browser window with the given HTML (no URL!). So if you HTML contains stuff like `<img src="foo.png">`, Chrome will not be able to load this image. Use absolute paths or data uris.

Hope this helps!

**Comment by maltoe** [comment]
@alvnrapada did you succeed? can we close this issue?

**Comment by alvnrapada** [comment]
> @alvnrapada did you succeed? can we close this issue?

Heyy, I tried your proposed solution but when downloading, pdf file is corrupted, but I found a react-pdf with react-phoenix and handle the pdf generation and downloading on the frontend side. Thank you so much for your help. Im gonna close this issue.
