### ISSUE TITLE
Fonts in html not visible in PDF

### ISSUE THREAD

**Issue by TheMaikXX** [bitcrowd/chromic_pdf#53]
Hello,
thanks for the work.
I have html code that I'd like to convert to pdf. It works well but fonts does not seem to be rendered.. instead I just see the default one (times new roman i guess). Also Font-Awesome icons are not visible.

Code for the job (inside my controller):
```
...
 Phoenix.View.render_to_string(MyAppWeb.MenuView, "menu-page.print.html", merged_assigns)
          |> prepare_menu_pdf()
          |> ChromicPDF.print_to_pdf(
               output: fn path ->
                 conn
                 |> send_download({:file, path}, filename: merged_assigns.filename <> ".pdf", disposition: :inline)
               end
             )
...
```

and `prepare_menu_pdf()`:
```
defp prepare_menu_pdf(string_content) when is_binary(string_content) do
    {:ok, styles} =
      Path.join(:code.priv_dir(:my_app_web), "static/css/menu-print-styles.css")
      |> File.read()

    {:ok, font_styles} =
      Path.join(:code.priv_dir(:my_app_web), "static/fonts/fira/fira.css")
      |> File.read()

    [
      content: [
        "<style>" <> styles <> "</style>",
        "<style>" <> font_styles <> "</style>",
        string_content
      ]
    ]
    |> ChromicPDF.Template.source_and_options()
  end
```

I have tried to download woff files mentioned in `fira/fira.css` (where those `@font-family`-ies are specified) so it can be available locally but no luck
FontAwesome is inserted with remote url..

Am I doing anything wrong?

Thanks in advance.

**Comment by andreasknoepfle** [comment]
I am not sure why remote URLs don't work, but we definitely have a project with base64 encoded url fonts working with chromic_pdf. 
```
@font-face {
  font-family: 'Somefont';
  font-style: normal;
  font-weight: light;
  src: url(data:font/woff;charset=utf-8;base64,....);
}
```

**Comment by maltoe** [comment]
I'm assuming you're starting `ChromicPDF` with its default options in your supervisor - the default configuration is to launch Chrome without, network connectivity (see [docs](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-running-in-online-mode)). This might very well prevent Chrome from fetching fonts from remote hosts.

But as @andreasknoepfle said, you'll probably be better off including the fonts as data uris in the styles regardless.

**Comment by TheMaikXX** [comment]
Thanks for the reply.

> I am not sure why remote URLs don't work, but we definitely have a project with base64 encoded url fonts working with chromic_pdf.
> 
> ```
> @font-face {
>   font-family: 'Somefont';
>   font-style: normal;
>   font-weight: light;
>   src: url(data:font/woff;charset=utf-8;base64,....);
> }
> ```
> 
> This might anyway be what you want, since unless you are using absolute path file URLs in your css , the fonts might be unavailable due to network traffic and downloaded every time a pdf is printed.

Ok. didnt know I can store it that way.. I must say that I was a little bit scared that the relative paths in my styles could not work..

Here is how it is specified: (with the `.woff2` file being physically next to the css file)
```
@font-face {
  font-family: 'Fira Sans Condensed';
  font-style: normal;
  font-weight: 400;
  src: local('Fira Sans Condensed Regular'), local('FiraSansCondensed-Regular'), url(./wEOhEADFm8hSaQTFG18FErVhsC9x-tarUfvtrftV.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}```

> I'm assuming you're starting `ChromicPDF` with its default options in your supervisor - the default configuration is to launch Chrome without network connectivity (see [docs](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-running-in-online-mode)). This might have been not such a great idea (maybe I'll change that to online by default soon), but it could very well prevent Chrome from fetching fonts from remote hosts.
> 
> But as @andreasknoepfle said, you'll probably be better off including the fonts as data uris in the styles regardless.

I see. thats good to know. I will make rest of the resources available offline as well..

**Comment by maltoe** [comment]
> (with the .woff2 file being physically next to the css file)

Yeah, that's not going to work like this. Especially since you used `ChromicPDF.Template.source_and_options()` which then sends the HTML source as a `{:html, ...}` tuple to `print_to_pdf`: This syntax replaces the HTML in the browser window (rather than navigation to a URL), so the browser does not have a clue where its content came from, neither from where it should fetch local (relative) resources. You would definitely need absolute URLs then in your stylesheet, as well as the `offline: false` parameter in the supervisor. (Alternatively the inline data-uri as said).

Please let us know if we can improve anything in the documentation, if you found confusing or missing or misplaced information.

**Comment by maltoe** [comment]
@TheMaikXX did you manage to embed the fonts? can we close this issue?

**Comment by TheMaikXX** [comment]
Oh yes. I managed to get it working.. thanks!
Sorry for not closing it earlier..
