### ISSUE TITLE
Integrating with paged.js

### ISSUE THREAD

**Issue by norpan** [bitcrowd/chromic_pdf#89]
Hi!
Currently we are using paged.js (pagedjs-cli) to generate pdfs using https://www.pagedjs.org/ since it supports a lot of new css to control the output that chrome doesn't support natively.

However, it's pretty slow to start a new node/chrome instance each time so I'm looking for alternatives.

I tried to instead using the pagedjs polyfill js in the web page and the following option (since that node is generated by pagedjs)
`wait_for: %{selector: ".pagedjs_pages", attribute: "style"}`

However, it seems it does not get a reply and timeouts. I guess this is because the node with class=".pagedjs_pages" does not exist at the start.

The corresponding code in pagedjs-cli is here: https://gitlab.pagedmedia.org/tools/pagedjs-cli/blob/master/src/printer.js#L220
`await page.waitForSelector(".pagedjs_pages");`

Any help would be much appreciated!

**Comment by andreasknoepfle** [comment]
Hello @norpan, 

it seems that paged has an [`after` hook]( https://gitlab.pagedmedia.org/tools/pagedjs#polyfill) that could be used for doing things after it has finished. Maybe you can create your own element in the DOM and add an attribute to the element with the `after` hook and use the`wait_for` option to wait for this element. Also note that the `wait_for` option is brand new and was just merged in today :), so maybe you have to use `chromic_pdf` from the `main` branch.

Cheers, 
Andi

**Comment by norpan** [comment]
Thanks, I hadn't considered that. I couldn't get the hook to work, but registering a handler and setting an attribute on the body worked. For anybody who has the same problem, here is what I did:

```
<script>
class PagedJsHandler extends Paged.Handler {
    constructor(chunker, polisher, caller) {
        super(chunker, polisher, caller);
    }

    afterRendered(pages) {
        document.body.setAttribute("rendered", "true")
    }
}
Paged.registerHandlers(PagedJsHandler)
</script>
```

and
```
          ChromicPDF.print_to_pdf({:url, "file://#{html_file}"},
            output: output_file,
            wait_for: %{selector: "body", attribute: "rendered"}
          )
```

Also, I had to increase the timeout for the session pool.

**Comment by maltoe** [comment]
The constructor isn't needed, is it?

**Comment by norpan** [comment]
I don't know, I just followed the example :)
