### ISSUE TITLE
Custom options to chromium

### ISSUE THREAD

**Issue by norpan** [bitcrowd/chromic_pdf#91]
Hi again!

We need to pass a custom option to chromium on startup, in this case we need `"--font-render-hinting=none"`. I don't see an immediate way to do this.

See https://github.com/puppeteer/puppeteer/issues/2410 for why we need font-render-hinting=none. In any case, it would be useful to be able to pass custom options.

**Comment by andreasknoepfle** [comment]
Hi @norpan,

I think at the moment there is no config option built in to do this, but I think we can add one. 

I guess the part in question is to be found here:
https://github.com/bitcrowd/chromic_pdf/blob/main/lib/chromic_pdf/pdf/chrome_impl.ex#L22-L30

We can have a look next time we are working on the project. In the meantime feel free to drop a PR for adding a config option yourself.

Cheers 
Andi

**Comment by norpan** [comment]
Thanks, I'll add it and make a PR. Would you prefer a specific option just for font-render-hinting (which maybe a niche case, I'm not sure) or a generic way to add any option to chromium on start?

Also, with regards to #92, I will do the same. I guess it's a matter of adding that command to print_to_pdf.ex.

**Comment by maltoe** [comment]
@norpan according to [this comment](https://github.com/puppeteer/puppeteer/issues/2410#issuecomment-382605477) in the puppeteer issue, puppeteer sets the `font-render-hinting` to `medium` by default? Is that a sane default to adopt for ChromicPDF as well?

**Comment by norpan** [comment]
I don't know what a sane default is. I would assume that Chrome's default would be the sane one but in our setting we've found that only "none" gives the correct result.

**Comment by maltoe** [comment]
🤔  the information in the puppeteer ticket and the [Chromium commit](https://github.com/chromium/chromium/commit/e1b855d4545dc4fff19cee500d7ce105126f3bd2) is odd and contradictory. My gutfeel is to make it a specific option and let it default to `none`. I'll check later tonight whether this has any (negative) effect on our templates.

**Comment by maltoe** [comment]
I tried a few PDF templates and they all looked exactly the same to me, no matter whether I used `none`, `medium` or `high`. Maybe Skia's subpixel glyph rendering is hard to notice though, unless it bites you. So from my perspective we could let it default to `none`, which seems to be the consensus on the issue you linked. *However*, puppeteer itself does not set any default value for it, plus it might still break font rendering for other ChromicPDF users (which I don't think there are too many, but nonetheless), so let's just add the option and not set it by default, please.

**Comment by norpan** [comment]
Yes, I think it matters what kind of fonts you use. The issue we had was that the spacing between characters was wrong when using a specific font. It only affects character spacing as far as I can see. The actual pixel rendering of the characters is not done by chrome, the font is embedded in the pdf as vectors.
